app = 'prod-yral-icpumpsearch'
primary_region = 'ams'
kill_signal = 'SIGINT'
kill_timeout = '5s'
swap_size_mb = 32768

[build]

[env]
  PORT = '50051'

[http_service]
  internal_port = 50051
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 50051

  [[services.ports]]
    port = 443
    handlers = ['tls']

    [services.ports.tls_options]
      alpn = ['h2']

  [services.concurrency]
    hard_limit = 20000
    soft_limit = 1000

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
