# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: search_rec.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'search_rec.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10search_rec.proto\x12\x06search\"$\n\rSearchRequest\x12\x13\n\x0binput_query\x18\x01 \x01(\t\"C\n\x0eSearchResponse\x12!\n\x05items\x18\x01 \x03(\x0b\x32\x12.search.SearchItem\x12\x0e\n\x06\x61nswer\x18\x02 \x01(\t\"\xaf\x01\n\nSearchItem\x12\x13\n\x0b\x63\x61nister_id\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x0c\n\x04host\x18\x03 \x01(\t\x12\x0c\n\x04link\x18\x04 \x01(\t\x12\x0c\n\x04logo\x18\x05 \x01(\t\x12\x12\n\ntoken_name\x18\x06 \x01(\t\x12\x14\n\x0ctoken_symbol\x18\x07 \x01(\t\x12\x0f\n\x07user_id\x18\x08 \x01(\t\x12\x12\n\ncreated_at\x18\t \x01(\t2J\n\rSearchService\x12\x39\n\x06Search\x12\x15.search.SearchRequest\x1a\x16.search.SearchResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'search_rec_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SEARCHREQUEST']._serialized_start=28
  _globals['_SEARCHREQUEST']._serialized_end=64
  _globals['_SEARCHRESPONSE']._serialized_start=66
  _globals['_SEARCHRESPONSE']._serialized_end=133
  _globals['_SEARCHITEM']._serialized_start=136
  _globals['_SEARCHITEM']._serialized_end=311
  _globals['_SEARCHSERVICE']._serialized_start=313
  _globals['_SEARCHSERVICE']._serialized_end=387
# @@protoc_insertion_point(module_scope)
